## Grouping

By 'group by' we are referring to a process involving one or more of the following steps:

* **Splitting** the data into groups based on some criteria
* **Applying** a function to each group independently
* **Combining** the results into a data structure

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                  'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
                  'C': np.random.randn(8),
                  'D': np.random.randn(8)})

In [5]:
df

     A      B         C         D
0  foo    one  0.069092 -0.280463
1  bar    one  1.356267 -0.120851
2  foo    two -0.274597  0.098109
3  bar  three -1.080416  0.328371
4  foo    two  0.678935 -0.054099
5  bar    two  2.002336 -1.754728
6  foo    one  0.458476  0.791929
7  foo  three  0.420486  1.260204

Grouping and then applying the **sum()** function to the resulting groups.

In [8]:
df.groupby('A').sum(numeric_only=True)

            C         D
A
bar  2.278186 -1.547208
foo  1.352392  1.815681

In [7]:
df.groupby('A')

Grouping by multiple columns forms a hierarchical index, and again we can apply the sum function.

In [9]:
df.groupby(['A', 'B']).sum()

                  C         D
A   B
bar one    1.356267 -0.120851
    three -1.080416  0.328371
    two    2.002336 -1.754728
foo one    0.527568  0.511466
    three  0.420486  1.260204
    two    0.404338  0.044010

#### Another example

In [10]:
df = pd.DataFrame(
    [
        ('bird', 'Falconiformes', 389.0),
        ('bird', 'Psittaciformes', 24.0),
        ('mammal', 'Carnivora', 80.2),
        ('mammal', 'Primates', np.nan),
        ('mammal', 'Carnivora', 58)
    ],
    index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
    columns=('class', 'order', 'max_speed')
)

In [11]:
df

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [12]:
g_class = df.groupby('class') # axis = 0
g_order = df.groupby('order', axis='columns') # axis = 1, axis = 'columns'
g_both = df.groupby(['class', 'order'])

/tmp/ipykernel_6177/3972504807.py:2: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  g_order = df.groupby('order', axis='columns') # axis = 1, axis = 'columns'

In [14]:
g_class.mean(numeric_only=True)

        max_speed
class
bird        206.5
mammal       69.1

In [18]:
g_both.mean()

                       max_speed
class  order
bird   Falconiformes       389.0
       Psittaciformes       24.0
mammal Carnivora            69.1
       Primates              NaN

#### Another example

In [34]:
data = {'school': ['HSU', 'HSU', 'HSU', 'OBU', 'OBU', 'SIU', 'SIU', 'SEU', 'SEU'],
       'professor': ['Bob', 'Jeff', 'Angela', 'Susan', 'Albert', 'Zelda', 'Alexa', 'Heather', 'Rebecca'],
       'publication': [10, 2, 30, 25, 0, 80, 4, 30, 15],
       'age': [76, 26, 30, 25, 50, 80, 40, 30, 50]}

df = pd.DataFrame(data)

In [35]:
df

  school professor  publication  age
0    HSU       Bob           10   76
1    HSU      Jeff            2   26
2    HSU    Angela           30   30
3    OBU     Susan           25   25
4    OBU    Albert            0   50
5    SIU     Zelda           80   80
6    SIU     Alexa            4   40
7    SEU   Heather           30   30
8    SEU   Rebecca           15   50

#### Groupby()

* use the .groupby() method to group rows together based off a column name
* Create a group based off of school

In [36]:
df.groupby('school') # Creates a DataFrameGroupBy object

In [37]:
by_school = df.groupby('school')

#### GroupBy and Aggregation Methods

* Use the aggregation methods on the grouped object

In [38]:
by_school.mean(numeric_only=True)

        publication   age
school
HSU            14.0  44.0
OBU            12.5  37.5
SEU            22.5  40.0
SIU            42.0  60.0

In [39]:
df.groupby('school').mean(numeric_only=True)

        publication   age
school
HSU            14.0  44.0
OBU            12.5  37.5
SEU            22.5  40.0
SIU            42.0  60.0

In [40]:
by_school.std(numeric_only=True)  # standard deviation

        publication        age
school
HSU       14.422205  27.784888
OBU       17.677670  17.677670
SEU       10.606602  14.142136
SIU       53.740115  28.284271

In [41]:
by_school.min()

       professor  publication  age
school
HSU       Angela            2   26
OBU       Albert            0   25
SEU      Heather           15   30
SIU        Alexa            4   40

In [42]:
by_school.max()

       professor  publication  age
school
HSU         Jeff           30   76
OBU        Susan           25   50
SEU      Rebecca           30   50
SIU        Zelda           80   80

In [43]:
by_school.count()

        professor  publication  age
school
HSU             3            3    3
OBU             2            2    2
SEU             2            2    2
SIU             2            2    2

#### Groupby + describe method

In [44]:
by_school.describe()

       publication                                                    age  \
             count  mean        std   min    25%   50%    75%   max count
school
HSU            3.0  14.0  14.422205   2.0   6.00  10.0  20.00  30.0   3.0
OBU            2.0  12.5  17.677670   0.0   6.25  12.5  18.75  25.0   2.0
SEU            2.0  22.5  10.606602  15.0  18.75  22.5  26.25  30.0   2.0
SIU            2.0  42.0  53.740115   4.0  23.00  42.0  61.00  80.0   2.0


        mean        std   min    25%   50%    75%   max
school
HSU     44.0  27.784888  26.0  28.00  30.0  53.00  76.0
OBU     37.5  17.677670  25.0  31.25  37.5  43.75  50.0
SEU     40.0  14.142136  30.0  35.00  40.0  45.00  50.0
SIU     60.0  28.284271  40.0  50.00  60.0  70.00  80.0

#### Groupby + describe method

In [46]:
type(by_school.describe().transpose())

pandas.core.frame.DataFrame

In [47]:
by_school.describe().transpose()

school                   HSU       OBU        SEU        SIU
publication count   3.000000   2.00000   2.000000   2.000000
            mean   14.000000  12.50000  22.500000  42.000000
            std    14.422205  17.67767  10.606602  53.740115
            min     2.000000   0.00000  15.000000   4.000000
            25%     6.000000   6.25000  18.750000  23.000000
            50%    10.000000  12.50000  22.500000  42.000000
            75%    20.000000  18.75000  26.250000  61.000000
            max    30.000000  25.00000  30.000000  80.000000
age         count   3.000000   2.00000   2.000000   2.000000
            mean   44.000000  37.50000  40.000000  60.000000
            std    27.784888  17.67767  14.142136  28.284271
            min    26.000000  25.00000  30.000000  40.000000
            25%    28.000000  31.25000  35.000000  50.000000
            50%    30.000000  37.50000  40.000000  60.000000
            75%    53.000000  43.75000  45.000000  70.000000
            max    76.000000  50.00000  50.000000  80.000000

In [48]:
df.groupby('school').describe()

       publication                                                    age  \
             count  mean        std   min    25%   50%    75%   max count
school
HSU            3.0  14.0  14.422205   2.0   6.00  10.0  20.00  30.0   3.0
OBU            2.0  12.5  17.677670   0.0   6.25  12.5  18.75  25.0   2.0
SEU            2.0  22.5  10.606602  15.0  18.75  22.5  26.25  30.0   2.0
SIU            2.0  42.0  53.740115   4.0  23.00  42.0  61.00  80.0   2.0


        mean        std   min    25%   50%    75%   max
school
HSU     44.0  27.784888  26.0  28.00  30.0  53.00  76.0
OBU     37.5  17.677670  25.0  31.25  37.5  43.75  50.0
SEU     40.0  14.142136  30.0  35.00  40.0  45.00  50.0
SIU     60.0  28.284271  40.0  50.00  60.0  70.00  80.0

In [49]:
df.groupby('school').describe().T

school                   HSU       OBU        SEU        SIU
publication count   3.000000   2.00000   2.000000   2.000000
            mean   14.000000  12.50000  22.500000  42.000000
            std    14.422205  17.67767  10.606602  53.740115
            min     2.000000   0.00000  15.000000   4.000000
            25%     6.000000   6.25000  18.750000  23.000000
            50%    10.000000  12.50000  22.500000  42.000000
            75%    20.000000  18.75000  26.250000  61.000000
            max    30.000000  25.00000  30.000000  80.000000
age         count   3.000000   2.00000   2.000000   2.000000
            mean   44.000000  37.50000  40.000000  60.000000
            std    27.784888  17.67767  14.142136  28.284271
            min    26.000000  25.00000  30.000000  40.000000
            25%    28.000000  31.25000  35.000000  50.000000
            50%    30.000000  37.50000  40.000000  60.000000
            75%    53.000000  43.75000  45.000000  70.000000
            max    76.000000  50.00000  50.000000  80.000000