## Introduction to Pandas

* Pandas is an open source library built on top of NumPy
* Allows fast analysis, cleaning and preparation of data
* High performance and productivity
* Built-in visualization capability
* Work with data from many sources

### Overview of Pandas Capabilities

* Series
* DataFrames
* Selection
* Missing Data
* Operations
* Merging, Joining and Concatenating
* GroupBy
* Reshaping Data and Pivot Tables
* Time Series
* Data Input/Output

#### Pandas 

This is a basic introduction to the pandas module.

First we start off with the customary imports.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

#### Object Creation

##### Series

    * Similar to NumPy array
        * Built on top of it
    * Can have exit labels


##### Series Creation

    * Here we will show a few ways to create series
        * Throughout the course we will be primarily dealing with DataFrames
        * DataFrames will be discussed shortly

    * Series can hold a variety of object types
    * Numbers, strings, etc.

Create a Series by passing a list, letting pandas create a default index value.

In [2]:
s = pd.Series([1, 2, 3, np.nan, 4, 5])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [3]:
s[4]

np.float64(4.0)

#### Note:

* Key to using a series is understanding its index
* Pandas makes use of these index names/numbers
* Allows fast lookups of information
* Works like a hash table or dictionary

In [4]:
s_1 = pd.Series([1, 2, 3, 4],
               ['USA', 'Germany', 'China', 'Japan'])

s_1

USA        1
Germany    2
China      3
Japan      4
dtype: int64

In [5]:
s_2 = pd.Series([1, 2, 5, 6], ['USA', 'Germany', 'Italy', 'China'])

s_2

USA        1
Germany    2
Italy      5
China      6
dtype: int64

In [6]:
s_2['Italy'] # Indexing is type dependent

np.int64(5)

In [7]:
s_2.index

Index(['USA', 'Germany', 'Italy', 'China'], dtype='str')

In [8]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
s_1.index

Index(['USA', 'Germany', 'China', 'Japan'], dtype='str')

In [10]:
labels = ['a', 'b', 'c']
s_3 = pd.Series(data=labels)

In [11]:
s_3

0    a
1    b
2    c
dtype: str

In [12]:
s_3[2]

'c'

##### Series

* Matches operation off of the index
* Creates NaN object where missing matches
* Integers converts to floats

In [13]:
s_1

USA        1
Germany    2
China      3
Japan      4
dtype: int64

In [14]:
s_2

USA        1
Germany    2
Italy      5
China      6
dtype: int64

In [15]:
s_1 + s_2

China      9.0
Germany    4.0
Italy      NaN
Japan      NaN
USA        2.0
dtype: float64

#### DataFrame Creation

Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns.

In [16]:
dates = pd.date_range('20210101', periods=10)

In [17]:
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10'],
              dtype='datetime64[us]', freq='D')

In [18]:
df = pd.DataFrame(np.random.randn(10,4),
                 index=dates,
                 columns=list('ABCD'))

In [19]:
df

                   A         B         C         D
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730
2021-01-04  0.241962 -1.913280 -1.724918 -0.562288
2021-01-05 -1.012831  0.314247 -0.908024 -1.412304
2021-01-06  1.465649 -0.225776  0.067528 -1.424748
2021-01-07 -0.544383  0.110923 -1.150994  0.375698
2021-01-08 -0.600639 -0.291694 -0.601707  1.852278
2021-01-09 -0.013497 -1.057711  0.822545 -1.220844
2021-01-10  0.208864 -1.959670 -1.328186  0.196861

Creating a DataFrame by passing a dictionary that can be converted to a series:

In [20]:
df2 = pd.DataFrame({
    'A': 1.,
    'B': pd.Timestamp('20260101'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(['test', 'train', 'test', 'train']),
    'F': 'foo'
})

In [21]:
df2

     A          B    C  D      E    F
0  1.0 2026-01-01  1.0  3   test  foo
1  1.0 2026-01-01  1.0  3  train  foo
2  1.0 2026-01-01  1.0  3   test  foo
3  1.0 2026-01-01  1.0  3  train  foo

The columns of the DataFrame have different `dtypes`.

In [22]:
df2.info()

<class 'pandas.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[us]
 2   C       4 non-null      float32
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      str
dtypes: category(1), datetime64[us](1), float32(1), float64(1), int32(1), str(1)
memory usage: 180.0 bytes

##### Viewing Data

Here is how to view the top and bottom rows of the frame:

In [23]:
df.head()

                   A         B         C         D
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730
2021-01-04  0.241962 -1.913280 -1.724918 -0.562288
2021-01-05 -1.012831  0.314247 -0.908024 -1.412304

In [25]:
df.tail()

                   A         B         C         D
2021-01-06  1.465649 -0.225776  0.067528 -1.424748
2021-01-07 -0.544383  0.110923 -1.150994  0.375698
2021-01-08 -0.600639 -0.291694 -0.601707  1.852278
2021-01-09 -0.013497 -1.057711  0.822545 -1.220844
2021-01-10  0.208864 -1.959670 -1.328186  0.196861

Display the index, columns:

In [27]:
df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10'],
              dtype='datetime64[us]', freq='D')

In [28]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [29]:
df.shape  # (Row, Column)

(10, 4)

We can convert our DataFrame (of floating-points) to a NumPy array.

In [30]:
df.to_numpy() # This can be a taxing operation in not all floats

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012, -1.32818605,  0.19686124]])

In [31]:
df.values

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818],
       [-0.01349722, -1.05771093,  0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012, -1.32818605,  0.19686124]])

In [32]:
df2.to_numpy()  # This has multiple dtypes

array([[1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-01-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

`describe()` shows a quick statistic summary of your data:

In [36]:
df.describe(), df.describe().T

(               A          B          C          D
 count  10.000000  10.000000  10.000000  10.000000
 mean   -0.046179  -0.485280  -0.306027  -0.037061
 std     0.701907   0.874335   1.060584   1.181041
 min    -1.012831  -1.959670  -1.724918  -1.424748
 25%    -0.525656  -0.866207  -1.090251  -1.056205
 50%    -0.123825  -0.229957  -0.532562  -0.134434
 75%     0.233688   0.048626   0.502648   0.669501
 max     1.465649   0.542560   1.579213   1.852278,
    count      mean       std       min       25%       50%       75%       max
 A   10.0 -0.046179  0.701907 -1.012831 -0.525656 -0.123825  0.233688  1.465649
 B   10.0 -0.485280  0.874335 -1.959670 -0.866207 -0.229957  0.048626  0.542560
 C   10.0 -0.306027  1.060584 -1.724918 -1.090251 -0.532562  0.502648  1.579213
 D   10.0 -0.037061  1.181041 -1.424748 -1.056205 -0.134434  0.669501  1.852278)

Transposing your data:

In [34]:
df.T

,2021-01-01,2021-01-02,2021-01-03,2021-01-04,2021-01-05,2021-01-06,2021-01-07,2021-01-08,2021-01-09,2021-01-10
A,0.496714,-0.234153,-0.469474,0.241962,-1.012831,1.465649,-0.544383,-0.600639,-0.013497,0.208864
B,-0.138264,-0.234137,0.542560,-1.913280,0.314247,-0.225776,0.110923,-0.291694,-1.057711,-1.959670
C,0.647689,1.579213,-0.463418,-1.724918,-0.908024,0.067528,-1.150994,-0.601707,0.822545,-1.328186
D,1.523030,0.767435,-0.465730,-0.562288,-1.412304,-1.424748,0.375698,1.852278,-1.220844,0.196861

Sorting by an axis:

In [37]:
df.sort_index(axis=0, ascending=True) # axis = 1 Columns (0, 1) == (Row, Column)

                   A         B         C         D
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730
2021-01-04  0.241962 -1.913280 -1.724918 -0.562288
2021-01-05 -1.012831  0.314247 -0.908024 -1.412304
2021-01-06  1.465649 -0.225776  0.067528 -1.424748
2021-01-07 -0.544383  0.110923 -1.150994  0.375698
2021-01-08 -0.600639 -0.291694 -0.601707  1.852278
2021-01-09 -0.013497 -1.057711  0.822545 -1.220844
2021-01-10  0.208864 -1.959670 -1.328186  0.196861

Sorting by values:

In [38]:
df.sort_values(by='B', ascending=False)

                   A         B         C         D
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730
2021-01-05 -1.012831  0.314247 -0.908024 -1.412304
2021-01-07 -0.544383  0.110923 -1.150994  0.375698
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-06  1.465649 -0.225776  0.067528 -1.424748
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-08 -0.600639 -0.291694 -0.601707  1.852278
2021-01-09 -0.013497 -1.057711  0.822545 -1.220844
2021-01-04  0.241962 -1.913280 -1.724918 -0.562288
2021-01-10  0.208864 -1.959670 -1.328186  0.196861

#### Selection

Selecting a single column yields a `Series`

In [39]:
df['A']

2021-01-01    0.496714
2021-01-02   -0.234153
2021-01-03   -0.469474
2021-01-04    0.241962
2021-01-05   -1.012831
2021-01-06    1.465649
2021-01-07   -0.544383
2021-01-08   -0.600639
2021-01-09   -0.013497
2021-01-10    0.208864
Freq: D, Name: A, dtype: float64

Selecting with `[]` slices the rows

In [40]:
df[0:3]

                   A         B         C         D
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730

In [42]:
df['20210101':'20210103']

                   A         B         C         D
2021-01-01  0.496714 -0.138264  0.647689  1.523030
2021-01-02 -0.234153 -0.234137  1.579213  0.767435
2021-01-03 -0.469474  0.542560 -0.463418 -0.465730

### DataFrames

#### Introduction

Throughout this book we work with DataFrames. A DataFrame is a two dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows and columns. 

We will get a brief insight on all these basic operations which can be performed on Pandas DataFrames:

1. Creating a DataFrame
2. Dealing with Rows and Columns
3. Indexing and Selecting Data
4. Working with Missing Data
5. Iterating over Rows and Columns

In the real world, a Pandas DataFrame will be created by loading the datasets from existing storage, storage can be SQL database, CSV file, and Excel file. Pandas DataFrame can be created from the lists, dictionary, and from a list of dictionary etc. DataFrame can be created in different ways. Here are some of the ways by which we can create a dataframe:

##### Creating a DataFrame using List:

DataFrame can be created using a single list or a list of lists.

In [43]:
import pandas as pd

Create a list of strings

In [44]:
state_lst = ['California', 'Texas', 'New York', 'Florida', 'Illinois']

Call the DataFrame constructor on the list.

In [45]:
df = pd.DataFrame(state_lst)

In [46]:
df

            0
0  California
1       Texas
2    New York
3     Florida
4    Illinois

#### Creating DataFrame from dict of ndarray/lists:

To create DataFrame from dict of ndarray/list, all the ndarray must be of same length. If index is passed, then the length index should be equal to the length of arrays. If no index is passed, then by default, index will be range(n) where n is the array length.

Initialize dictionary of lists.

In [47]:
data = {'state': ['California', 'Texas', 'New York', 'Florida', 'Illinois'],
       'pop': [3833252, 26448193, 19651127, 19552860, 12885135],
       'area': [423967, 695662, 141297, 170312, 149995]}

In [51]:
data

{'state': ['California', 'Texas', 'New York', 'Florida', 'Illinois'],
 'pop': [3833252, 26448193, 19651127, 19552860, 12885135],
 'area': [423967, 695662, 141297, 170312, 149995]}

In [48]:
df = pd.DataFrame(data)

In [49]:
df.set_index(keys='state', inplace=True)

In [50]:
df

                 pop    area
state
California   3833252  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12885135  149995

#### Dealing with Rows and Columns

A DataFrame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. We can perform basic operations on rows/columns like selecting, deleting, adding and renaming.

##### Column Selection:

The individual series that make up the columns of the DataFrame can be accessed via dictionary style indexing of the column name:

In [52]:
df['area']

state
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Equivalently, we can use attribute-style access with column names that are strings:

In [53]:
df.area

state
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Though this is a useful shorthand, keep in mind that it does not work for all cases! For example, if the column names are not strings, or if the column names conflict with methods of the DataFrame, this attribute-style access is not possible. For example, the DataFrame has a `pop()` method, so `data.pop` will point to this rather than the 'pop' column:

In [56]:
df.pop is df['pop']

False

In [57]:
df.pop

<bound method DataFrame.pop of                  pop    area
state
California   3833252  423967
Texas       26448193  695662
New York    19651127  141297
Florida     19552860  170312
Illinois    12885135  149995>

In [58]:
df['pop']

state
California     3833252
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12885135
Name: pop, dtype: int64

In particular, you should avoid the temptation to try column assignment via attribute (i.e., use `data['pop'] = z` rather than `data.pop = z`).
Like with the Series objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [59]:
df['density'] = df['pop'] / df['area']

In [60]:
df

                 pop    area     density
state
California   3833252  423967    9.041392
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121
Illinois    12885135  149995   85.903763

##### Select Multiple Columns

In [61]:
df[['density', 'area']]

               density    area
state
California    9.041392  423967
Texas        38.018740  695662
New York    139.076746  141297
Florida     114.806121  170312
Illinois     85.903763  149995

In [63]:
my_cols = ['area', 'pop']
df[my_cols]

              area       pop
state
California  423967   3833252
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12885135

#### Row Selection:

Pandas provides a unique method to retrieve rows from a DataFrame. `DataFrame.loc[]` method is used to review rows from Pandas DataFrame. Rows can also be selected by passing integer location to an `iloc[]` function.

In [62]:
df.loc['California']

pop        3.833252e+06
area       4.239670e+05
density    9.041392e+00
Name: California, dtype: float64

##### Indexing and Selecting Data

Indexing in pandas means simply selecting particular rows and columns of data from a DataFrame. Indexing could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns. Indexing can also be known as Subset Selection.

##### Indexing a DataFrame using indexer operator []:

Indexing operator is used to prefer to the square brackets following an object. The `.loc` and `.iloc` indexers also use the indexing operator to make selections. In this indexing operator to refer to `df[]`.

##### Selecting Single Columns

In order to select a single column, we simply put the name of the column in-between the brackets.

In [64]:
df['density']

state
California      9.041392
Texas          38.018740
New York      139.076746
Florida       114.806121
Illinois       85.903763
Name: density, dtype: float64

#### Selecting Multiple Colums

In [66]:
df[['density', 'area']] # Use list object for multiple rows

               density    area
state
California    9.041392  423967
Texas        38.018740  695662
New York    139.076746  141297
Florida     114.806121  170312
Illinois     85.903763  149995

#### Indexing a DataFrame using .iloc[]:

This function allows us to retrieve rows and columns by position. In order to do that, we will need to specify the positions of the rows that we want, and the positions of the columns that we want as well. The df.iloc indexer is very similar to df.loc but only uses integer locations to make its selections.

##### Selecting a single row

In order to select a single row using `.iloc[]`, we can pass a single integer to `.iloc[]` function.

In [67]:
df.iloc[2]

pop        1.965113e+07
area       1.412970e+05
density    1.390767e+02
Name: New York, dtype: float64

##### Selecting multiple rows

In [68]:
df.iloc[[0,2]]

                 pop    area     density
state
California   3833252  423967    9.041392
New York    19651127  141297  139.076746