## Understanding Joins and Mergers

### Inner Join

The simplest type of join is the inner join. An inner join matches pairs of observations whenever their keys are equal:

The most important property of an inner join is that unmatched rows are not included in the result. This means that generally inner joins are usually not appropriate for use in analysis because it's too easy to lose observations.

### Outer Joins

An inner join keeps observations that appear in both the tables. An outer join keeps observations that appear in at least one of the tables. There are three types of outer joins:

* A left join keeps all observations in x.
* A right join keeps all observations in y.
* A full join kepps all observations in x and y.

These joins work by adding an additional "virtual" observation to each table. This observation has a key that always matches (if no other key matches), and a value filled with NA.

The most commonly used join is the left join: you use this whenever you look up additional data from another table, because it preserves the original observations even there isn't a match.

#### Duplicate keys

So far all the diagrams have assumed that the keys are unique. But that's not always the case. This section explains what happens when the keys are not unique. There are two possibilities:

1. One table has duplicate keys. This is useful when you want to add in additional information as there is typically a one-to-many relationship.
2. Both tables have duplicate keys. This is usually an error because in neither table do the keys uniquely identify an observation. When you join duplicated keys, you get all possible combinations, the Cartesian product:

#### Defining the key columns

So far, the pairs of tables have always been joined by a single variable, and that variable has the same name in both tables. That constraint was encoded by `on="key"`. You can use other values for by to connect the tables in other ways.

### Merge

#### Concat

Pandas provides various facilities for easily combining together Series and DataFrame objects with various kinds of set logic for the indexes and relational algebra funtionality in the case of join/merges-type operations.

Concatenating pandas objects together with `concat()`:

In [2]:
import pandas as pd
import numpy as np
np.random.seed()
df = pd.DataFrame(np.random.randn(10,4))

In [3]:
df

          0         1         2         3
0 -0.096054  0.575236 -1.176115 -0.333863
1 -1.387884  2.224268 -1.246507 -1.449061
2  1.310595  0.209264 -0.483168  0.746276
3  0.345311  1.013012  0.937935 -0.983547
4 -0.399956  0.084363 -1.791688 -0.160948
5 -1.301436  0.733679 -1.271290  1.417590
6 -0.595442 -0.656322 -0.733546 -1.106411
7 -1.278364 -0.797295  1.023620 -0.092934
8 -1.137874 -0.873137  0.257922  1.348219
9 -0.218395 -0.531090 -0.692861 -0.986303

In [4]:
df[:3]

          0         1         2         3
0 -0.096054  0.575236 -1.176115 -0.333863
1 -1.387884  2.224268 -1.246507 -1.449061
2  1.310595  0.209264 -0.483168  0.746276

In [5]:
pieces = [df[:3], df[3:7], df[7:]]  # Break it into pieces

In [6]:
pieces

[          0         1         2         3
 0 -0.096054  0.575236 -1.176115 -0.333863
 1 -1.387884  2.224268 -1.246507 -1.449061
 2  1.310595  0.209264 -0.483168  0.746276,
           0         1         2         3
 3  0.345311  1.013012  0.937935 -0.983547
 4 -0.399956  0.084363 -1.791688 -0.160948
 5 -1.301436  0.733679 -1.271290  1.417590
 6 -0.595442 -0.656322 -0.733546 -1.106411,
           0         1         2         3
 7 -1.278364 -0.797295  1.023620 -0.092934
 8 -1.137874 -0.873137  0.257922  1.348219
 9 -0.218395 -0.531090 -0.692861 -0.986303]

In [7]:
pd.concat(pieces)

          0         1         2         3
0 -0.096054  0.575236 -1.176115 -0.333863
1 -1.387884  2.224268 -1.246507 -1.449061
2  1.310595  0.209264 -0.483168  0.746276
3  0.345311  1.013012  0.937935 -0.983547
4 -0.399956  0.084363 -1.791688 -0.160948
5 -1.301436  0.733679 -1.271290  1.417590
6 -0.595442 -0.656322 -0.733546 -1.106411
7 -1.278364 -0.797295  1.023620 -0.092934
8 -1.137874 -0.873137  0.257922  1.348219
9 -0.218395 -0.531090 -0.692861 -0.986303

### Joins

SQL style merges.

In [8]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1,2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4,5]})

In [9]:
left

   key  lval
0  foo     1
1  foo     2

In [10]:
right

   key  rval
0  foo     4
1  foo     5

In [11]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

#### Another Example

In [12]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1,2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4,5]})

In [14]:
left

   key  lval
0  foo     1
1  bar     2

In [15]:
right

   key  rval
0  foo     4
1  bar     5

In [16]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  bar     2     5

#### Append

Append rows to a dataframe.

In [17]:
df = pd.DataFrame(np.random.randn(8,4), columns=['A', 'B', 'C', 'D'])

In [18]:
df

          A         B         C         D
0 -0.773208  0.493474 -2.463787  0.635439
1  0.421440  0.289367 -1.575293 -0.809025
2  0.948043  1.521488  1.151705  1.635452
3  0.450271  0.957356 -1.038345 -0.488488
4 -0.854971  0.199260 -1.482323 -0.354778
5  0.566845  0.171333 -1.013291 -0.629205
6  0.331951 -0.326474 -1.119389  1.236035
7 -0.492999  0.466358  1.028331  0.089071

In [19]:
s = df.iloc[3]

In [32]:
df

          A         B         C         D
0 -0.773208  0.493474 -2.463787  0.635439
1  0.421440  0.289367 -1.575293 -0.809025
2  0.948043  1.521488  1.151705  1.635452
3  0.450271  0.957356 -1.038345 -0.488488
4 -0.854971  0.199260 -1.482323 -0.354778
5  0.566845  0.171333 -1.013291 -0.629205
6  0.331951 -0.326474 -1.119389  1.236035
7 -0.492999  0.466358  1.028331  0.089071

In [40]:
s = pd.DataFrame(s).T
s

          A         B         C         D
3  0.450271  0.957356 -1.038345 -0.488488

In [43]:
pd.concat([df, s], axis=0, ignore_index=False)

          A         B         C         D
0 -0.773208  0.493474 -2.463787  0.635439
1  0.421440  0.289367 -1.575293 -0.809025
2  0.948043  1.521488  1.151705  1.635452
3  0.450271  0.957356 -1.038345 -0.488488
4 -0.854971  0.199260 -1.482323 -0.354778
5  0.566845  0.171333 -1.013291 -0.629205
6  0.331951 -0.326474 -1.119389  1.236035
7 -0.492999  0.466358  1.028331  0.089071
3  0.450271  0.957356 -1.038345 -0.488488